version: '3.8'

services:
  matrix-pilot:
    build: .
    container_name: matrix_pilot_dev
    ports:
      - "5000:5000"
    environment:
      - APP_PIN=123456
      - TZ=Asia/Shanghai
      # 开启 Flask 开发模式，支持 Python 代码热重载
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      # 【核心魔法】将电脑当前目录(.) 挂载到容器内的 /app 目录
      - .:/app
    restart: unless-stopped